# Generated by Django 3.1 on 2020-09-09 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favorites',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite', to='cookbook.Recipe'),
        ),
    ]
